version: '3.8'
services:
  pgdb:
    image: 'postgres:16'
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5423:5432
    environment:
      - POSTGRES_USER=abzil
      - POSTGRES_PASSWORD=abzil123
      - POSTGRES_DB=imsdb
  backend:
    build: ./
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb

volumes:
  pg-data: